# -*- coding: utf-8 -*-
"""fmc sales 2021 fix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19AUtde8-JPRiU_c-zvbuJvS9BoXgLopC

#**Inisiasi Data**
"""

import pandas as pd
data = pd.read_csv('sales_21.csv')
data.info()
df = pd.DataFrame(data)
print(df)

data_deskripsi = df.describe()
print("\nStatistik Deskriptif Data:")
print(data_deskripsi)

"""#**Data Cleaning**"""

import pandas as pd
import re
df['Barang'] = df['Barang'].fillna('').astype(str).str.strip().str.lower()

sapaan = {'pak', 'bapak', 'bu', 'ibu', 'kak', 'mba', 'mbak', 'mas', 'bpk', '-'}
def bersihkan_nama(nama):
    nama = re.sub(r'[^\w\s]', '', str(nama).lower())
    tokens = nama.split()
    tokens_bersih = [word for word in tokens if word not in sapaan]
    return ' '.join(tokens_bersih)
df['Nama Pelanggan'] = df['Nama Pelanggan'].apply(bersihkan_nama)
print(df[['Nama Pelanggan','Barang']])

# Mengecek data duplikat
duplicates = df[df.duplicated()]
duplicate_count = df.duplicated().sum()
print(f'Jumlah data duplikat: {duplicate_count}')
print(duplicates)

# Menghapus data duplikat
df_cleaned = df.drop_duplicates()
duplicates = df_cleaned[df_cleaned.duplicated()]
duplicate_count = df_cleaned.duplicated().sum()
print(f'Jumlah data duplikat: {duplicate_count}')
df_cleaned.shape

# Menghapus kolom yang tidak diperlukan
df_cleaned = df_cleaned.drop(columns=['Status Pelanggan', 'Supplier', 'Customer Service','Bulan','Tanggal'])
df_cleaned.info()

print(df_cleaned)

# Deteksi missing value
df_cleaned.isnull()
missingvalue_count = df_cleaned.isnull().sum()
print(f'Jumlah missing value:\n {missingvalue_count}')

# Menghapus baris yang terdapat missing value
df_cleaned = df_cleaned.dropna()
df_cleaned.shape

#Type casting
df_cleaned['Kuantitas'] = pd.to_numeric(df_cleaned['Kuantitas'], errors='coerce')
df_cleaned = df_cleaned.dropna(subset=['Kuantitas'])

# Mengonversi kolom jumlah menjadi integer
df_cleaned['Kuantitas'] = df_cleaned['Kuantitas'].astype(int)
# Mengonversi kolom "Penjualan" ke float
df_cleaned['Pendapatan'] = df_cleaned['Pendapatan'].replace({'Rp': '', ',': ''}, regex=True)
df_cleaned['Pendapatan'] = pd.to_numeric(df_cleaned['Pendapatan'], errors='coerce')

# Verifikasi perubahan tipe data
print(df_cleaned.dtypes)
df_cleaned.shape

# df_cleaned.to_csv('data_cleaning_21.csv', index=False)
# from google.colab import files
# files.download('data_cleaning_21.csv')

"""#**Ekstraksi Fitur FMC**"""

# Menghitung nilai frequency (F) untuk keseluruhan tahun
fmc_f = df_cleaned.groupby(by=['Barang'], as_index=False)['Jumlah'].sum()
fmc_f.columns = ['Barang', 'Frequency']

# Menghitung nilai monetary (M) untuk keseluruhan tahun
fmc_m = df_cleaned.groupby(by=['Barang'], as_index=False)['Penjualan '].sum()
fmc_m.columns = ['Barang', 'Monetary']

# Menghitung nilai customer variety (C) untuk keseluruhan tahun
fmc_c = df_cleaned.groupby(['Barang'])['Dari'].nunique().reset_index()
fmc_c.columns = ['Barang', 'Customer Variety']

# Menggabungkan data Frequency, Monetary, dan Customer Variety
fmc = fmc_f.merge(fmc_m, on='Barang').merge(fmc_c, on='Barang')

# Menampilkan hasil ekstraksi FMC
print(fmc)

# Statistik deskriptif fitur FMC
statistik_deskriptif = fmc[['Frequency', 'Monetary', 'Customer Variety']].describe()
print("\nStatistik Deskriptif:")
print(statistik_deskriptif)

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure(figsize=(13, 13))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot dengan tiga sumbu
ax.scatter(fmc['Frequency'], fmc['Monetary'], fmc['Customer Variety'], c='blue', marker='o',  s=175)

# Label sumbu
ax.set_xlabel('Frekuensi')
ax.set_ylabel('Monetary')
ax.set_zlabel('Customer Variety')
ax.set_title('Scatter Plot 3D Segmentasi Produk')

plt.show()

#fmc.to_csv('fmc_21.csv', index=False)
#from google.colab import files
#files.download('fmc_21.csv')

"""#**Normalisasi Data**"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
columns_to_normalize = ['Frequency', 'Monetary', 'Customer Variety']
fmc[columns_to_normalize] = scaler.fit_transform(fmc[columns_to_normalize])
print("\nNormalisasi FMC penjualan 2021:")
print(fmc)

# Statistik deskriptif fitur FMC yang ternormalisasi
statistik_deskriptif = fmc[['Frequency', 'Monetary', 'Customer Variety']].describe()
print("\nStatistik Deskriptif:")
print(statistik_deskriptif)

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=5, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=6, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=7, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

kmeans = KMeans(n_clusters=8, random_state=42)
kmeans.fit(fmc[columns_to_normalize])
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=2)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=3)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=4)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=5)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=6)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=7)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

ahc = AgglomerativeClustering(linkage='ward',n_clusters=8)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('fmc_21.csv', index=False)
from google.colab import files
files.download('fmc_21.csv')

fmc.to_csv('elbow_21.csv', index=False)
from google.colab import files
files.download('elbow_21.csv')

"""#**Evaluasi Hasil KMeans dengan Silhouete Score**"""

from sklearn.metrics import silhouette_score

k_values = range(2, 10)
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(fmc[columns_to_normalize])

    cluster_labels = kmeans.labels_

    # silhouette score
    silhouette_avg = silhouette_score(fmc[columns_to_normalize], cluster_labels)
    print("k-clusters={0}, silhouette score = {1}".format(k, silhouette_avg))

# Menerapkan K-Means Clustering untuk k=2
optimal_k = 2
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
kmeans.fit(fmc[columns_to_normalize])

"""#**Evaluasi Hasil AHC dengan Silhouete Score**"""

k_values = range(2, 11)

for num_clusters in k_values:
    ahc = AgglomerativeClustering(n_clusters=num_clusters)
    Ahc_labels = ahc.fit_predict(fmc[columns_to_normalize])

    # Calculate and print silhouette score
    silhouette_avg = silhouette_score(fmc[columns_to_normalize], Ahc_labels)
    print("k-clusters={0}, silhouette score = {1}".format(num_clusters, silhouette_avg))

optimal_k = 2
fmc['KMeans_Cluster'] = kmeans.fit_predict(fmc[columns_to_normalize])
ahc = AgglomerativeClustering(n_clusters=optimal_k)
fmc['AHC_Cluster'] = ahc.fit_predict(fmc[columns_to_normalize])
print(fmc)
print(fmc['KMeans_Cluster'].value_counts())
print(fmc['AHC_Cluster'].value_counts())

fmc.to_csv('hasil_21 new.csv', index=False)
from google.colab import files
files.download('hasil_21 new.csv')

import plotly.express as px

data = pd.DataFrame(fmc, columns=['Frequency', 'Monetary', 'Customer Variety','KMeans_Cluster'])

# Plotting 3D scatter menggunakan plotly
fig = px.scatter_3d(
    data,
    x='Frequency',
    y='Monetary',
    z='Customer Variety',
    color='KMeans_Cluster',
    title='Scatter Plot 3D Hasil KMeans Clustering'
)

fig.show()

data = pd.DataFrame(fmc, columns=['Frequency', 'Monetary', 'Customer Variety','KMeans_Cluster', 'AHC_Cluster'])

# Plotting 3D scatter menggunakan plotly
fig = px.scatter_3d(
    data,
    x='Frequency',
    y='Monetary',
    z='Customer Variety',
    color='AHC_Cluster',
    title='Scatter Plot 3D Hasil AHC Clustering'
)

fig.show()

from mpl_toolkits.mplot3d import Axes3D

# Plotting
fig = plt.figure(figsize=(13, 13))
ax = fig.add_subplot(111, projection='3d')
colors = ['r', 'b', 'y', 'c', 'm']

# Menggunakan kolom 'KMeans_Cluster' untuk visualisasi cluster
for cluster_label, color in zip(fmc['KMeans_Cluster'].unique(), colors):
    cluster_data = fmc[fmc['KMeans_Cluster'] == cluster_label]
    ax.scatter(
        cluster_data['Frequency'],
        cluster_data['Monetary'],
        cluster_data['Customer Variety'],
        c=color,
        label=f'Cluster {cluster_label}',
        s=175  # Ukuran marker
    )

# Menambahkan label untuk sumbu
ax.set_xlabel('Frequency')
ax.set_ylabel('Monetary')
ax.set_zlabel('Customer Variety')

# Menambahkan judul dan legenda
plt.title('Scatter Plot 3D Hasil Clustering Berdasarkan K-Means')
plt.legend()
plt.show()

# Plotting
fig = plt.figure(figsize=(15, 13))
ax = fig.add_subplot(111, projection='3d')
colors = ['r', 'b', 'y', 'c', 'm']


# Menggunakan kolom 'AHC_Cluster' untuk visualisasi cluster
for cluster_label, color in zip(data['AHC_Cluster'].unique(), colors):
    cluster_data = data[data['AHC_Cluster'] == cluster_label]
    ax.scatter(
        cluster_data['Frequency'],
        cluster_data['Monetary'],
        cluster_data['Customer Variety'],
        c=color,
        label=f'Cluster {cluster_label}',
        s=175
    )

# Menambahkan label untuk sumbu
ax.set_xlabel('Frequency')
ax.set_ylabel('Monetary')
ax.set_zlabel('Customer Variety')

# Menambahkan judul dan legenda
plt.title('Scatter Plot 3D Hasil Clustering Berdasarkan AHC')
plt.legend()
plt.show()

cluster_averages_KMeans = fmc.groupby('KMeans_Cluster')[['Frequency', 'Monetary', 'Customer Variety']].mean()
cluster_averages_AHC = fmc.groupby('AHC_Cluster')[['Frequency', 'Monetary', 'Customer Variety']].mean()
print("Rata-rata nilai Frequency, Monetary, dan Customer Variety untuk tiap cluster dengan K-Means:")
print(cluster_averages_KMeans)
print("Rata-rata nilai Frequency, Monetary, dan Customer Variety untuk tiap cluster dengan AHC:")
print(cluster_averages_AHC)